# NAME: Jianzhi Liu
# EMAIL: ljzprivate@yahoo.com
# ID: 204742214

CC = gcc
CFLAGS = -Wall -Wextra
ID = 204742214

default: lab1a.c
	$(CC) $(CFLAGS) -o lab1a lab1a.c
clean:
	rm -f lab1a lab1a-$(ID).tar.gz
dist:
	tar -czf lab1a-$(ID).tar.gz lab1a.c Makefile README

