# NAME: Jianzhi Liu
# EMAIL: ljzprivate@yahoo.com
# ID: 204742214

ID = 204742214

default:
	tar -czf lab4a-$(ID).tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

